name: Build and Deploy

on:
  workflow_dispatch: 
    inputs:
      branch:
        description: "Select the branch to deploy"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12"

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Project
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Replace with your build output directory
